openapi: 3.0.0
info:
  title: API de gestion d’utilisateurs
  version: 1.0.0
paths:
  /users:
    get:
      summary: Listes des Utilisateurs
      parameters:
        - name: page
          in: query
          description: Numero de page
          required: false
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          description: Nombre d'utilisateur par page
          required: false
          schema:
            type: integer
            example: 20
      responses:
        "200":
          description: liste des utilisateurs retrouvés.
          content:
            applicaton/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: mauvais types de paramètres fournis.
          content:
            applicaton/json:
              schema: 
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad types for provided query parameters"

components:
  schemas:
    User:
      type: object
      properties: 
        id: 
          type: integer
          example: 1 
        name:
          type: string
          example: "Christian"
        email: 
          type: string
          example: "Christian@gmail.com"
